Common = [
    "Alaskan Klee Kai",
    "American Bulldog",
    "American Leopard Hound",
    "Appenzeller Sennenhund",
    "Australian Kelpie",
    "Australian Stumpy Tail Cattle Dog",
    "Azawakh",
    "Barbado da Terceira",
    "Barbet",
    "Basset Fauve de Bretagne",
    "Bavarian Mountain Scent Hound",
    "Belgian Laekenois",
    "Biewer Terrier",
    "Bohemian Shepherd",
    "Bolognese",
    "Bracco Italiano",
    "Braque du Bourbonnais",
    "Braque Francais Pyrenean",
    "Broholmer",
    "Carolina Dog",
    "Catahoula Leopard Dog",
    "Caucasian Shepherd Dog",
    "Central Asian Shepherd Dog",
    "Croatian Sheepdog",
    "Czechoslovakian Vlcak",
    "Danish Swedish Farmdog",
    "Deutscher Wachtelhund",
    "Dogo Argentino",
    "Drentsche Patrijshond",
    "Drever",
    "Dutch Shepherd",
    "Estrela Mountain Dog",
    "Eurasier",
    "French Spaniel",
    "German Longhaired Pointer",
    "German Spitz",
    "Hamiltonstovare",
    "Hanoverian Scenthound",
    "Hokkaido",
    "Hovawart",
    "Jagdterrier",
    "Japanese Akitainu",
    "Japanese Spitz",
    "Japanese Terrier",
    "Jindo",
    "Kai Ken",
    "Kishu Ken",
    "Kromfohrlander",
    "Lancashire Heeler",
    "Lapponian Herder",
    "Mountain Cur",
    "Mudi",
    "Norrbottenspets",
    "Perro de Presa Canario",
    "Peruvian Inca Orchid",
    "Porcelaine",
    "Portuguese Podengo",
    "Portuguese Pointer",
    "Portuguese Sheepdog",
    "Pudelpointer",
    "Pyrenean Mastiff",
    "Rafeiro do Alentejo",
    "Russian Toy",
    "Russian Tsvetnaya Bolonka",
    "Schapendoes",
    "Segugio Italiano",
    "Shikoku",
    "Slovakian Wirehaired Pointer",
    "Slovensky Cuvac",
    "Slovensky Kopov",
    "Small Munsterlander",
    "Spanish Mastiff",
    "Stabyhoun",
    "Swedish Lapphund",
    "Taiwan Dog",
    "Teddy Roosevelt Terrier",
    "Thai Ridgeback",
    "Tornjak",
    "Tosa",
    "Transylvanian Hound",
    "Treeing Tennessee Brindle",
    "Volpino Italiano",
    "Wetterhoun",
    "Working Kelpie"
]


Uncommon = [
    "Airedale Terrier",
    "Akita",
    "Alaskan Malamute",
    "Australian Cattle Dog",
    "Australian Shepherd",
    "Basset Hound",
    "Beagle",
    "Belgian Malinois",
    "Bernese Mountain Dog",
    "Bichon Frise",
    "Bloodhound",
    "Border Collie",
    "Boston Terrier",
    "Boxer",
    "Brittany",
    "Bull Terrier",
    "Bulldog",
    "Bullmastiff",
    "Cairn Terrier",
    "Cane Corso",
    "Cardigan Welsh Corgi",
    "Cavalier King Charles Spaniel",
    "Chesapeake Bay Retriever",
    "Chihuahua",
    "Chinese Shar-Pei",
    "Cocker Spaniel",
    "Collie",
    "Dachshund",
    "Dalmatian",
    "Doberman Pinscher",
    "Dogue de Bordeaux",
    "English Cocker Spaniel",
    "English Springer Spaniel",
    "French Bulldog",
    "German Shepherd Dog",
    "German Shorthaired Pointer",
    "German Wirehaired Pointer",
    "Golden Retriever",
    "Great Dane",
    "Great Pyrenees",
    "Havanese",
    "Labrador Retriever",
    "Maltese",
    "Mastiff",
    "Miniature American Shepherd",
    "Miniature Pinscher",
    "Miniature Schnauzer",
    "Newfoundland",
    "Papillon",
    "Pembroke Welsh Corgi",
    "Pomeranian",
    "Poodle (Miniature)",
    "Poodle (Standard)",
    "Poodle (Toy)",
    "Portuguese Water Dog",
    "Pug",
    "Rhodesian Ridgeback",
    "Rottweiler",
    "Saint Bernard",
    "Samoyed",
    "Scottish Terrier",
    "Shetland Sheepdog",
    "Shiba Inu",
    "Shih Tzu",
    "Siberian Husky",
    "Soft Coated Wheaten Terrier",
    "Vizsla",
    "Weimaraner",
    "West Highland White Terrier",
    "Whippet",
    "Wirehaired Pointing Griffon",
    "Yorkshire Terrier"
]


Rare = [
    "Afghan Hound",
    "American Eskimo Dog",
    "American Staffordshire Terrier",
    "Anatolian Shepherd Dog",
    "Basenji",
    "Bearded Collie",
    "Beauceron",
    "Belgian Sheepdog",
    "Belgian Tervuren",
    "Black Russian Terrier",
    "Bluetick Coonhound",
    "Boerboel",
    "Border Terrier",
    "Borzoi",
    "Bouvier des Flandres",
    "Boykin Spaniel",
    "Brussels Griffon",
    "Chinese Crested",
    "Chow Chow",
    "Coton de Tulear",
    "English Setter",
    "English Toy Spaniel",
    "Flat-Coated Retriever",
    "Giant Schnauzer",
    "Gordon Setter",
    "Greater Swiss Mountain Dog",
    "Irish Setter",
    "Irish Terrier",
    "Irish Wolfhound",
    "Italian Greyhound",
    "Japanese Chin",
    "Keeshond",
    "Kerry Blue Terrier",
    "Lagotto Romagnolo",
    "Leonberger",
    "Lhasa Apso",
    "Miniature Bull Terrier",
    "Neapolitan Mastiff",
    "Norfolk Terrier",
    "Norwegian Elkhound",
    "Norwich Terrier",
    "Nova Scotia Duck Tolling Retriever",
    "Old English Sheepdog",
    "Parson Russell Terrier",
    "Pekingese",
    "Pointer",
    "Rat Terrier",
    "Russell Terrier",
    "Saluki",
    "Schipperke",
    "Silky Terrier",
    "Smooth Fox Terrier",
    "Spinone Italiano",
    "Staffordshire Bull Terrier",
    "Standard Schnauzer",
    "Tibetan Spaniel",
    "Tibetan Terrier",
    "Toy Fox Terrier",
    "Welsh Springer Spaniel",
    "Welsh Terrier",
    "Wire Fox Terrier"
]


Ultra = [
    "Affenpinscher",
    "American English Coonhound",
    "American Hairless Terrier",
    "American Water Spaniel",
    "Australian Terrier",
    "Bedlington Terrier",
    "Berger Picard",
    "Black and Tan Coonhound",
    "Briard",
    "Clumber Spaniel",
    "Curly-Coated Retriever",
    "Entlebucher Mountain Dog",
    "Field Spaniel",
    "Finnish Lapphund",
    "German Pinscher",
    "Glen of Imaal Terrier",
    "Greyhound",
    "Ibizan Hound",
    "Icelandic Sheepdog",
    "Irish Red and White Setter",
    "Irish Water Spaniel",
    "Komondor",
    "Kuvasz",
    "Lakeland Terrier",
    "Löwchen",
    "Manchester Terrier (Standard)",
    "Manchester Terrier (Toy)",
    "Nederlandse Kooikerhondje",
    "Norwegian Buhund",
    "Petit Basset Griffon Vendéen",
    "Pharaoh Hound",
    "Plott Hound",
    "Polish Lowland Sheepdog",
    "Portuguese Podengo Pequeno",
    "Puli",
    "Pumi",
    "Redbone Coonhound",
    "Scottish Deerhound",
    "Sealyham Terrier",
    "Spanish Water Dog",
    "Tibetan Mastiff",
    "Treeing Walker Coonhound",
    "Wirehaired Vizsla",
    "Xoloitzcuintli"
]


Legendary = [
    "American Foxhound",
    "Bergamasco Sheepdog",
    "Canaan Dog",
    "Cesky Terrier",
    "Chinook",
    "Cirneco dell\'Etna",
    "Dandie Dinmont Terrier",
    "English Foxhound",
    "Finnish Spitz",
    "Grand Basset Griffon Vendéen",
    "Harrier",
    "Otterhound",
    "Pyrenean Shepherd",
    "Skye Terrier",
    "Sussex Spaniel",
    "Swedish Vallhund"
]


Deity = [
    "Norwegian Lundehund",
    "Sloughi",
    "Yakutian Laika",
    "Karelian Bear Dog",
    "Romanian Mioritic Shepherd Dog",
    "Tofupupper"
]


Success = {
    "success" : 50,
    "max" : 322,
    "common" : 1,
    "uncommon" : 201,
    "rare" : 301,
    "ultra" : 315,
    "legendary" : 320,
    "deity" : 322
}