Common = [
    "Oxygen",
    "Silicon",
    "Aluminium",
    "Iron",
    "Calcium",
    "Sodium",
    "Magnesium",
    "Potassium",
    "Titanium",
    "Hydrogen",
    "Phosphorus",
    "Manganese",
    "Fluorine",
    "Barium",
    "Strontium",
    "Sulfur",
    "Carbon",
    "Zirconium",
    "Chlorine",
    "Vanadium",
    "Chromium",
    "Rubidium",
    "Nickel",
    "Zinc",
    "Cerium",
    "Copper",
    "Neodymium",
    "Lanthanum",
    "Yttrium",
    "Cobalt",
    "Scandium",
    "Lithium",
    "Niobium",
    "Nitrogen",
    "Gallium",
    "Lead",
    "Boron",
    "Thorium",
    "Praseodymium",
    "Samarium",
    "Gadolinium",
    "Dysprosium",
    "Argon",
    "Erbium",
    "Ytterbium",
    "Caesium",
    "Hafnium",
    "Beryllium",
    "Uranium",
    "Bromine"
]

Uncommon = [
    "Tin",
    "Europium",
    "Tantalum",
    "Arsenic",
    "Germanium",
    "Holmium",
    "Tungsten",
    "Molybdenum",
    "Terbium",
    "Thallium",
    "Lutetium",
    "Thulium",
    "Iodine",
    "Indium",
    "Antimony",
    "Cadmium",
    "Mercury",
    "Silver",
    "Selenium",
    "Palladium",
    "Bismuth",
    "Helium",
    "Neon",
    "Platinum",
    "Gold",
    "Osmium",
    "Ruthenium",
    "Rhodium",
    "Tellurium",
    "Iridium",
    "Rhenium",
    "Krypton",
    "Xenon",
    "Protactinium",
    "Radium",
    "Technetium",
    "Actinium",
    "Polonium",
    "Plutonium",
    "Neptunium",
    "Radon",
    "Francium"
]

Rare = [
    "Promethium",
    "Astatine",
    "Americium",
    "Curium",
    "Berkelium",
    "Californium",
    "Einsteinium",
    "Fermium",
    "Mendelevium",
    "Nobelium",
    "Lawrencium"
]

Ultra = [
    "Rutherfordium",
    "Dubnium",
    "Seaborgium",
    "Bohrium",
    "Hassium",
    "Meitnerium",
    "Darmstadtium",
    "Roentgenium",
    "Copernicium",
    "Nihonium"
]

Legendary = [
    "Flerovium",
    "Moscovium",
    "Livermorium"
]

Deity = [
    "Tennessine",
    "Oganesson"
]

Success = {
    "success" : 70,
    "max" : 118,
    "common" : 1,
    "uncommon" : 51,
    "rare" : 93,
    "ultra" : 104,
    "legendary" : 114,
    "deity" : 117
}
